name: Freeze Application

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
        cache: pip

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    
    - name: Freeze application
      run: python -m PyInstaller --distpath "./dist/PBR-2-Source/" -y build.spec

    - uses: actions/upload-artifact@v4
      with:
        name: PBR-2-Source-linux
        path: ./dist/PBR-2-Source
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64
        cache: pip

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    
    - name: Freeze application
      run: python -m PyInstaller --distpath "./dist/PBR-2-Source/" -y build.spec

    - uses: actions/upload-artifact@v4
      with:
        name: PBR-2-Source-win64
        path: ./dist/PBR-2-Source
        if-no-files-found: error
